# Generated by Django 4.2.5 on 2023-10-09 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50, null=True)),
                ('Sobrenome', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=255)),
                ('Login', models.CharField(max_length=20, null=True)),
                ('Senha', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('ZonaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome_da_Zona', models.CharField(max_length=30, null=True)),
                ('Tipo_Zona', models.CharField(max_length=50, null=True)),
                ('Quantidade_Ocorrencias', models.IntegerField(null=True)),
                ('Data_Ocorrencia', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('OcorrenciaID', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Ocorrencia', models.CharField(max_length=50, null=True)),
                ('Bairro', models.CharField(max_length=30, null=True)),
                ('Longitude', models.CharField(max_length=30, null=True)),
                ('Latitude', models.CharField(max_length=30, null=True)),
                ('Data_Hora', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Descricao', models.TextField()),
                ('Anexos', models.BooleanField()),
                ('User_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='seguranca.usuario')),
                ('Zonas_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='seguranca.zonas')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
    ]
